---
title: "dbplyrでデータサイエンス100本ノック(構造化データ加工編)."
author: "Shena"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
description: "This is a minimal example of using
  the bookdown package to write a book."
github-repo: 'Shena4746/datascience-100knocks-preprocess-R'
---

```{r setup, eval = TRUE, include=FALSE}
rm(list = ls())
gc(reset = TRUE)
gc(reset = TRUE)
knitr::opts_chunk$set(eval = TRUE, echo = TRUE, warning = FALSE)
```

# 前置き

## 概要
このドキュメントは, [データサイエンス100本ノック（構造化データ加工編）](https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess) を WSL2 + Ubuntu20.04 + R で解いた記録. dbplyr パッケージを利用して, 極力データを手元にダウンロードせずに, DB 上の操作だけで完結する手段をとる. なお, 全問の回答は載せていない. 特に, SQL の方が楽にできる問題や公式回答と似た回答になった問題の多くはスキップしている.

以下の記事は大変参考にさせていただきました. 公開に感謝します.
[【R】データサイエンス100本ノック（構造化データ加工編）をtidyverseでやった](https://qiita.com/eitsupi/items/ae0476605cbaa3b04fc7)

## dbplyr とは {#about-dbplyr}

詳細は \@ref(references) - References の文献に譲り, ここでは大雑把に書く. dbplyr とは, 
dplyr の文法で書いたデータ加工処理を接続先に合わせた適切な SQL クエリに翻訳し, DBI (Database Interface) などのバックエンドとして働くパッケージと連携して, その SQL の実行結果を返してくれるパッケージ. dbplyr は SQL の SELECT 文に相当する処理のみを翻訳する.
以下は, dbplyr を利用する際の典型的な作業フローの概要. サンプルコードは \@ref(setup) - 準備にある.

- **接続**: DBI と 接続先 DB に対応した専用パッケージ (e.g., RPostgres, RSQLite) で接続を確立
- **テーブルへの参照取得**: 接続した DB 上のテーブルへの参照を取得 
- **処理内容の作成**: 参照先のテーブルに対して, dplyr の文法でデータ処理加工を書く
- **SQLへの翻訳**: dbplyr がその処理内容を SQL に変換する
- **SQL の実行**: DBI 等のバックエンドパッケージがその SQL を実行し, 結果への参照を返す

直接 SQL を書くのではなく dbplyr を使うメリットとしては,

- SQL の方言に関わらず, 統一的な書き方ができる
- 多くの場合, コードがより簡潔になる
- R - SQL 間の言語またぎが起こりづらい

などが挙げられる. 一方, デメリットとしては, 

- 利用するパッケージがいくつかあるので, それについての知識が追加で必要
- SQL に比べて文献が少ない
- 翻訳可能な R コード群を整理するまでに試行錯誤が必要
- 初等的と思える処理でも翻訳できないことがある

などがある. ただし, これらの点, 特に1, 2点目は, 100本ノックを倒す目的の範囲内ならばほとんど問題にならない.
厄介なのは後半の2点である. この翻訳可能性問題を回避するために, サイズが十分小さくなるまで加工したデータをローカルマシンにダウンロードし, 通常の R での加工処理に帰着させる方法をよく取る. この場合, 上述の作業フローに以下の手続きが追加される.

- **データのダウンロード**: DB 上のデータを dbplyr で手元にダウンロードする
- **ローカルでのデータ加工**: ダウンロードデータを通常のRデータとしてさらに加工する(パッケージ使い放題)
- **データのアップロード (optional) **: DBI などのバックエンドパッケージを使ってそのデータを DB 上にアップロードする
